### ISSUE TITLE
Does not recognize its own built-in module

### ISSUE THREAD

**Issue by goodluck821** [Navezjt/ComfyUI_roop#1]
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1.4\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_roop\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_roop\nodes.py", line 3, in <module>
    from scripts.faceswap import FaceSwapScript, get_models
ModuleNotFoundError: No module named 'scripts.faceswap'

Cannot import K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_roop module for custom nodes: No module named 'scripts.faceswap'

**Comment by goodluck821** [comment]
OK!
